---

- name: Remove trusted user keys & certificate files
  vars:
    ssh_files:
      - "{{ ssh_user_ca_keys }}"
      - "{{ ssh_host_key }}-cert.pub"
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ ssh_files }}"

- name: Remove trusted user keys & certificate from SSH config
  vars:
    ssh_config:
      - param: "TrustedUserCAKeys"
        value: "{{ ssh_user_ca_keys }}"
      - param: "HostCertificate"
        value: "{{ ssh_host_key }}-cert.pub"
  lineinfile:
    path: "{{ sshd_conf }}"
    line: "{{ item['param'] }} {{ item['value'] }}"
    state: absent
  notify: reload ssh
  loop: "{{ ssh_config }}"

