---

- name: Reload ssh (RedHat)
  listen: reload ssh
  service:
      name: sshd
      state: reloaded
  when:
    - ansible_os_family == "RedHat"

- name: Reload ssh (Debian)
  listen: reload ssh
  service:
      name: ssh
      state: reloaded
  when:
    - ansible_os_family == "Debian"

