---
# defaults file for anisble-role-vault-ssh

vault_admintokenfile: "~/.hashicorp_admin_token.json"
vault_addr: "10.1.42.10"
vault_port: "8200"
ssh_public_key: "/etc/ssh/trusted-user-ca-keys.pem"
sshd_conf: "/etc/ssh/sshd_config"

vault_user: "vault"
vault_group: "vault"
vault_keysfile: "~/.hashicorp_vault_keys.json"
vault_provisionertokenfile: "~/.hashicorp_provisioner_token.json"
audit_path: "/var/log/vault"
